[theme]
primaryColor = "#6f4e37"
backgroundColor = "#FCF4EC"
secondaryBackgroundColor = "#402218"
textColor = "#2C1A0E"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "auto"

[logger]
level = "info"

[server]
headless = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
